-- =====================================================
-- LABORATORY WORK #3 (DML) - FIXED VERSION
-- PostgreSQL. Run PART 0 ONCE, then tasks 1..15 in order.
-- =====================================================


-- =====================================================
-- PART 0. PREPARATION (run once, no screenshot needed)
-- =====================================================

-- (a) ID columns are plain INT, so make them auto-generated
ALTER TABLE airline        ALTER COLUMN airline_id        ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 3);
ALTER TABLE airport        ALTER COLUMN airport_id        ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 4);
ALTER TABLE baggage_check  ALTER COLUMN baggage_check_id  ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 6);

-- (b) created_at / updated_at are NOT NULL, so give them defaults
ALTER TABLE airline       ALTER COLUMN created_at SET DEFAULT NOW(), ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE airport       ALTER COLUMN created_at SET DEFAULT NOW(), ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE baggage_check ALTER COLUMN created_at SET DEFAULT NOW(), ALTER COLUMN updated_at SET DEFAULT NOW();

-- (c) Tasks 8 and 10 need NULL values, so allow NULL there
ALTER TABLE airline ALTER COLUMN airline_code DROP NOT NULL;
ALTER TABLE airport ALTER COLUMN state DROP NOT NULL;

-- (d) Test data so that the DELETE/UPDATE tasks have something to work on
-- Flight that arrives in 2024 (task 5)
INSERT INTO flights VALUES
(4, '2024-05-01 08:00:00', '2024-05-01 10:00:00', 1, 2, 'A1', 'B1', 1,
 '2024-05-01 08:05:00', '2024-05-01 10:02:00', NOW(), NOW());

-- Cheap ticket (task 7)
INSERT INTO booking VALUES
(106, 1, 1, 'Website', NOW(), NOW(), 'Confirmed', 5000.00);

-- Old / March-2024 baggage checks (tasks 9 and 15)
INSERT INTO baggage_check (check_result, created_at, updated_at, booking_id, passenger_id) VALUES
('Not checked', '2023-05-10 12:00:00', NOW(), 101, 1),
('Not checked', '2023-01-15 09:30:00', NOW(), 102, 2),
('Not checked', '2024-03-15 10:00:00', NOW(), 103, 3),
('Not checked', '2024-03-20 16:45:00', NOW(), 104, 4);

-- Airports for tasks 10 and 14
INSERT INTO airport (airport_name, country, state, city) VALUES
('Mlawe Airport',  'Poland',    NULL,             'Mlawe'),
('Kepuh Airport',  'Indonesia', NULL,             'Kepuh'),
('Mlawe Airport 2','Poland',    'Mazovia',        'Mlawe'),   -- has state, must NOT be deleted
('Heathrow',       'UK',        'Greater London', 'London'),
('Haneda',         'Japan',     'Kanto',          'Tokyo');


-- =====================================================
-- TASK 1. Generate and insert 200 random rows (airport)
-- =====================================================
SELECT count(*) AS before_count FROM airport;

INSERT INTO airport (airport_name, country, state, city)
SELECT 'Airport ' || i,
       'Country ' || (random()*30)::int,
       'State '   || (random()*50)::int,
       'City '    || (random()*100)::int
FROM generate_series(1, 200) AS i;

SELECT count(*) AS after_count FROM airport;
SELECT * FROM airport ORDER BY airport_id DESC LIMIT 20;


-- =====================================================
-- TASK 2. Add airline "KazAir" (Kazakhstan)
-- =====================================================
INSERT INTO airline (airline_name, airline_country)
VALUES ('KazAir', 'Kazakhstan');

SELECT * FROM airline;


-- =====================================================
-- TASK 3. Update KazAir country to Turkey
-- =====================================================
UPDATE airline
SET airline_country = 'Turkey'
WHERE airline_name = 'KazAir';

SELECT * FROM airline;


-- =====================================================
-- TASK 4. Add three airlines at once
-- =====================================================
INSERT INTO airline (airline_name, airline_country) VALUES
('AirEasy', 'France'),
('FlyHigh', 'Brazil'),
('FlyFly',  'Poland');

SELECT * FROM airline;


-- =====================================================
-- TASK 5. Delete all flights whose arrival is in 2024
-- =====================================================
SELECT flight_id, sch_arrival_time FROM flights;   -- before

DELETE FROM flights
WHERE EXTRACT(YEAR FROM sch_arrival_time) = 2024;

SELECT flight_id, sch_arrival_time FROM flights;   -- after


-- =====================================================
-- TASK 6. Increase all ticket prices by 15%
-- =====================================================
SELECT booking_id, ticket_price FROM booking ORDER BY booking_id;   -- before

UPDATE booking
SET ticket_price = ticket_price * 1.15;

SELECT booking_id, ticket_price FROM booking ORDER BY booking_id;   -- after


-- =====================================================
-- TASK 7. Delete all tickets where price < 10000
-- =====================================================
SELECT booking_id, ticket_price FROM booking WHERE ticket_price < 10000;   -- before

DELETE FROM booking
WHERE ticket_price < 10000;

SELECT booking_id, ticket_price FROM booking ORDER BY booking_id;          -- after


-- =====================================================
-- TASK 8. Default code 'UNK' where airline_code is NULL
-- =====================================================
SELECT airline_id, airline_code, airline_name FROM airline ORDER BY airline_id;   -- before

UPDATE airline
SET airline_code = 'UNK'
WHERE airline_code IS NULL;

SELECT airline_id, airline_code, airline_name FROM airline ORDER BY airline_id;   -- after


-- =====================================================
-- TASK 9. Delete baggage checks before 2023-06-01 with 'Not checked'
-- =====================================================
SELECT * FROM baggage_check ORDER BY baggage_check_id;   -- before

DELETE FROM baggage_check
WHERE created_at < '2023-06-01'
  AND check_result = 'Not checked';

SELECT * FROM baggage_check ORDER BY baggage_check_id;   -- after


-- =====================================================
-- TASK 10. Delete airports: state IS NULL and city Mlawe / Kepuh
-- =====================================================
SELECT * FROM airport WHERE city IN ('Mlawe', 'Kepuh');   -- before

DELETE FROM airport
WHERE state IS NULL
  AND city IN ('Mlawe', 'Kepuh');

SELECT * FROM airport WHERE city IN ('Mlawe', 'Kepuh');   -- after


-- =====================================================
-- TASK 11. Insert unchecked baggage record and return id + created_at
-- =====================================================
INSERT INTO baggage_check (check_result, booking_id, passenger_id)
VALUES ('Not checked', 105, 5)
RETURNING baggage_check_id, created_at;

SELECT * FROM baggage_check ORDER BY baggage_check_id DESC LIMIT 5;


-- =====================================================
-- TASK 12. Convert all airline countries to uppercase
-- =====================================================
SELECT airline_id, airline_name, airline_country FROM airline ORDER BY airline_id;   -- before

UPDATE airline
SET airline_country = UPPER(airline_country);

SELECT airline_id, airline_name, airline_country FROM airline ORDER BY airline_id;   -- after


-- =====================================================
-- TASK 13. Update airline_id = 5
-- =====================================================
SELECT * FROM airline WHERE airline_id = 5;   -- before

UPDATE airline
SET airline_name    = 'Global Airways',
    airline_country = 'United Kingdom',
    updated_at      = CURRENT_DATE
WHERE airline_id = 5;

SELECT * FROM airline WHERE airline_id = 5;   -- after


-- =====================================================
-- TASK 14. Set state = 'Capital District' for Astana, London, Tokyo
-- =====================================================
SELECT * FROM airport WHERE city IN ('Astana', 'London', 'Tokyo');   -- before

UPDATE airport
SET state = 'Capital District'
WHERE city IN ('Astana', 'London', 'Tokyo');

SELECT * FROM airport WHERE city IN ('Astana', 'London', 'Tokyo');   -- after


-- =====================================================
-- TASK 15. March 2024 'Not checked' -> 'Checked'
-- =====================================================
SELECT * FROM baggage_check
WHERE created_at >= '2024-03-01' AND created_at < '2024-04-01';   -- before

UPDATE baggage_check
SET check_result = 'Checked'
WHERE created_at >= '2024-03-01' AND created_at < '2024-04-01'
  AND check_result = 'Not checked';

SELECT * FROM baggage_check
WHERE created_at >= '2024-03-01' AND created_at < '2024-04-01';   -- after
