-- =====================================================================
-- Laboratory work 3 — DML   (PostgreSQL)
-- Schema = Lab 2 DDL (after renames):
--   airline(airline_id, airline_code, airline_name, airline_country, created_at, updated_at)
--   airport(airport_id, airport_name, country, state, city, created_at, updated_at)
--   flights, booking, booking_flight, baggage, baggage_check,
--   boarding_pass, passengers, security_check
-- Run the whole script top to bottom on EMPTY tables (as after Lab 2).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. PREPARATION (run once)
-- ---------------------------------------------------------------------
-- TRUNCATE airline, airport, passengers, flights, booking, booking_flight,
--          baggage, baggage_check, boarding_pass, security_check CASCADE;  -- only if tables are not empty

-- 0.1 Auto-generated IDs (task 11 needs "newly generated baggage_check_id").
--     SKIP this block if your id columns are already SERIAL / IDENTITY.
ALTER TABLE airline        ALTER COLUMN airline_id        ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE airport        ALTER COLUMN airport_id        ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE passengers     ALTER COLUMN passenger_id      ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE flights        ALTER COLUMN flight_id         ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE booking        ALTER COLUMN booking_id        ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE booking_flight ALTER COLUMN booking_flight_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE baggage        ALTER COLUMN baggage_id        ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE baggage_check  ALTER COLUMN baggage_check_id  ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE boarding_pass  ALTER COLUMN boarding_pass_id  ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE security_check ALTER COLUMN security_check_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 0.2 created_at / updated_at get the current time automatically
ALTER TABLE airline        ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE airport        ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE passengers     ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE flights        ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE booking        ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE booking_flight ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE baggage        ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE baggage_check  ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE boarding_pass  ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE security_check ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();

-- 0.3 Tasks 8 and 10 talk about NULL values, but Lab 2 made every column NOT NULL.
--     So these two columns must allow NULL:
ALTER TABLE airline ALTER COLUMN airline_code DROP NOT NULL;
ALTER TABLE airport ALTER COLUMN state        DROP NOT NULL;


-- =====================================================================
-- TASK 1. Generate and insert 200 random rows (200 per table)
--         Order matters: parents first, children after (foreign keys).
-- =====================================================================
INSERT INTO airline (airline_id, airline_code, airline_name, airline_country)
SELECT g,
       CASE WHEN random() < 0.2 THEN NULL                      -- ~20% NULL codes (for task 8)
            ELSE upper(substr(md5(random()::text), 1, 3)) END,
       'Airline_' || g,
       (ARRAY['Kazakhstan','Turkey','France','Germany','Japan','Brazil','Poland','Italy'])[floor(random()*8)+1]
FROM generate_series(1, 200) g;

INSERT INTO airport (airport_id, airport_name, country, state, city)
SELECT g,
       'Airport_' || g,
       (ARRAY['Kazakhstan','Turkey','France','Germany','Japan','Brazil','Poland','Italy'])[floor(random()*8)+1],
       'State_' || (floor(random()*20)+1)::int,
       'City_'  || g
FROM generate_series(1, 200) g;

INSERT INTO passengers (passenger_id, first_name, last_name, date_of_birth, gender,
                        country_of_citizenship, country_of_residence, passport_number)
SELECT g,
       (ARRAY['Aidar','Aruzhan','Nurlan','Dana','John','Maria','Ali','Emma'])[floor(random()*8)+1],
       (ARRAY['Smith','Ivanov','Kim','Nurpeisov','Brown','Garcia','Sato','Muller'])[floor(random()*8)+1],
       date '1960-01-01' + (random()*15000)::int,
       (ARRAY['Male','Female'])[floor(random()*2)+1],
       (ARRAY['Kazakhstan','Turkey','France','Germany','Japan'])[floor(random()*5)+1],
       (ARRAY['Kazakhstan','Turkey','France','Germany','Japan'])[floor(random()*5)+1],
       'P' || lpad(g::text, 8, '0')
FROM generate_series(1, 200) g;

-- flights: dates spread over 2023-2024 (so some arrive in 2024 — task 5)
INSERT INTO flights (flight_id, sch_departure_time, sch_arrival_time, departing_airport_id, arriving_airport_id,
                     departing_gate, arriving_gate, airline_id, act_departure_time, act_arrival_time)
SELECT g, dep, dep + interval '3 hours',
       a, a % 200 + 1,                                          -- arriving airport differs from departing
       'G' || (floor(random()*30)+1)::int, 'G' || (floor(random()*30)+1)::int,
       floor(random()*200)::int + 1,
       dep + (random()*30) * interval '1 minute',
       dep + interval '3 hours' + (random()*40) * interval '1 minute'
FROM (SELECT g,
             timestamp '2023-01-01' + random() * interval '730 days' AS dep,
             floor(random()*200)::int + 1 AS a
      FROM generate_series(1, 200) g) s;

-- booking: price 3000..83000 (max after +15% = 95450 < 99999.99, fits decimal(7,2))
INSERT INTO booking (booking_id, flight_id, passenger_id, booking_platform, status, ticket_price)
SELECT g,
       floor(random()*200)::int + 1,
       floor(random()*200)::int + 1,
       (ARRAY['Website','Mobile app','Agency'])[floor(random()*3)+1],
       (ARRAY['Confirmed','Pending','Cancelled'])[floor(random()*3)+1],
       round((3000 + random()*80000)::numeric, 2)
FROM generate_series(1, 200) g;

INSERT INTO booking_flight (booking_flight_id, booking_id, flight_id)
SELECT booking_id, booking_id, flight_id FROM booking;

INSERT INTO baggage (baggage_id, weight_in_kg, booking_id)
SELECT g, round((1 + random()*40)::numeric, 2), g
FROM generate_series(1, 200) g;

INSERT INTO baggage_check (baggage_check_id, check_result, created_at, updated_at, booking_id, passenger_id)
SELECT booking_id,
       (ARRAY['Not checked','Not checked','Checked','Failed'])[floor(random()*4)+1],
       ts, ts, booking_id, passenger_id
FROM (SELECT booking_id, passenger_id,
             timestamp '2023-01-01' + random() * interval '730 days' AS ts
      FROM booking) b;

INSERT INTO boarding_pass (boarding_pass_id, booking_id, seat, boarding_time)
SELECT g, g,
       (floor(random()*30)+1)::int || (ARRAY['A','B','C','D','E','F'])[floor(random()*6)+1],
       timestamp '2023-01-01' + random() * interval '730 days'
FROM generate_series(1, 200) g;

INSERT INTO security_check (security_check_id, check_result, passenger_id)
SELECT g, (ARRAY['Passed','Failed'])[floor(random()*2)+1], g
FROM generate_series(1, 200) g;

-- Because ids were inserted manually, move every identity counter past the max id
DO $$
DECLARE t text[];
BEGIN
  FOREACH t SLICE 1 IN ARRAY ARRAY[
    ['airline','airline_id'], ['airport','airport_id'], ['passengers','passenger_id'],
    ['flights','flight_id'], ['booking','booking_id'], ['booking_flight','booking_flight_id'],
    ['baggage','baggage_id'], ['baggage_check','baggage_check_id'],
    ['boarding_pass','boarding_pass_id'], ['security_check','security_check_id']]
  LOOP
    EXECUTE format('SELECT setval(pg_get_serial_sequence(%L, %L), (SELECT COALESCE(MAX(%I),0)+1 FROM %I), false)',
                   t[1], t[2], t[2], t[1]);
  END LOOP;
END $$;

-- Test airports needed by tasks 10 and 14 (added AFTER flights, so no flight references them)
INSERT INTO airport (airport_name, country, state, city) VALUES
    ('Mlawe Airport',        'Poland',         NULL,      'Mlawe'),
    ('Kepuh Airport',        'Indonesia',      NULL,      'Kepuh'),
    ('Astana International', 'Kazakhstan',     'Akmola',  'Astana'),
    ('London Heathrow',      'United Kingdom', 'England', 'London'),
    ('Tokyo Haneda',         'Japan',          'Kanto',   'Tokyo');

-- check
SELECT 'airline' t, count(*) FROM airline UNION ALL SELECT 'airport', count(*) FROM airport
UNION ALL SELECT 'passengers', count(*) FROM passengers UNION ALL SELECT 'flights', count(*) FROM flights
UNION ALL SELECT 'booking', count(*) FROM booking UNION ALL SELECT 'baggage_check', count(*) FROM baggage_check;


-- =====================================================================
-- TASK 2. Add airline "KazAir" from "Kazakhstan"
-- =====================================================================
INSERT INTO airline (airline_name, airline_country) VALUES ('KazAir', 'Kazakhstan');
SELECT * FROM airline WHERE airline_name = 'KazAir';

-- =====================================================================
-- TASK 3. Update KazAir country to "Turkey"
-- =====================================================================
UPDATE airline SET airline_country = 'Turkey' WHERE airline_name = 'KazAir';
SELECT * FROM airline WHERE airline_name = 'KazAir';

-- =====================================================================
-- TASK 4. Add three airlines at once
-- =====================================================================
INSERT INTO airline (airline_name, airline_country) VALUES
    ('AirEasy', 'France'),
    ('FlyHigh', 'Brazil'),
    ('FlyFly',  'Poland');
SELECT * FROM airline WHERE airline_name IN ('AirEasy','FlyHigh','FlyFly');

-- =====================================================================
-- TASK 5. Delete all flights whose arrival is in 2024
--         (actual arrival; use sch_arrival_time if your teacher means scheduled)
--         Child rows (booking, booking_flight, baggage, ...) must be deleted first,
--         otherwise the foreign keys block the delete.
-- =====================================================================
CREATE TEMP TABLE del_flights AS
    SELECT flight_id FROM flights
    WHERE act_arrival_time >= '2024-01-01' AND act_arrival_time < '2025-01-01';

CREATE TEMP TABLE del_bookings AS
    SELECT booking_id FROM booking      WHERE flight_id IN (SELECT flight_id FROM del_flights)
    UNION
    SELECT booking_id FROM booking_flight WHERE flight_id IN (SELECT flight_id FROM del_flights);

DELETE FROM baggage_check  WHERE booking_id IN (SELECT booking_id FROM del_bookings);
DELETE FROM baggage        WHERE booking_id IN (SELECT booking_id FROM del_bookings);
DELETE FROM boarding_pass  WHERE booking_id IN (SELECT booking_id FROM del_bookings);
DELETE FROM booking_flight WHERE booking_id IN (SELECT booking_id FROM del_bookings)
                              OR flight_id  IN (SELECT flight_id  FROM del_flights);
DELETE FROM booking        WHERE booking_id IN (SELECT booking_id FROM del_bookings);
DELETE FROM flights        WHERE flight_id  IN (SELECT flight_id  FROM del_flights);

SELECT count(*) AS flights_arriving_2024 FROM flights
WHERE act_arrival_time >= '2024-01-01' AND act_arrival_time < '2025-01-01';   -- must be 0

-- =====================================================================
-- TASK 6. Increase the price of all tickets in booking by 15%
-- =====================================================================
UPDATE booking SET ticket_price = ticket_price * 1.15;
SELECT booking_id, ticket_price FROM booking ORDER BY booking_id LIMIT 10;

-- =====================================================================
-- TASK 7. Delete all tickets where price is less than 10000
-- =====================================================================
DELETE FROM baggage_check  WHERE booking_id IN (SELECT booking_id FROM booking WHERE ticket_price < 10000);
DELETE FROM baggage        WHERE booking_id IN (SELECT booking_id FROM booking WHERE ticket_price < 10000);
DELETE FROM boarding_pass  WHERE booking_id IN (SELECT booking_id FROM booking WHERE ticket_price < 10000);
DELETE FROM booking_flight WHERE booking_id IN (SELECT booking_id FROM booking WHERE ticket_price < 10000);
DELETE FROM booking WHERE ticket_price < 10000;
SELECT count(*) AS cheap_tickets_left FROM booking WHERE ticket_price < 10000;   -- must be 0

-- =====================================================================
-- TASK 8. Set code 'UNK' for airlines where airline_code is NULL
-- =====================================================================
UPDATE airline SET airline_code = 'UNK' WHERE airline_code IS NULL;
-- optional: so that future rows get it automatically
-- ALTER TABLE airline ALTER COLUMN airline_code SET DEFAULT 'UNK';
SELECT count(*) AS null_codes_left FROM airline WHERE airline_code IS NULL;      -- must be 0

-- ---- test data for tasks 9 and 15 (makes sure matching rows still exist after tasks 5 and 7)
INSERT INTO baggage_check (check_result, created_at, updated_at, booking_id, passenger_id)
SELECT 'Not checked', v.ts, v.ts, b.booking_id, b.passenger_id
FROM (SELECT booking_id, passenger_id, row_number() OVER (ORDER BY booking_id) rn FROM booking) b
JOIN (VALUES (1, timestamp '2023-03-10'),
             (2, timestamp '2024-03-15'),
             (3, timestamp '2024-03-20')) v(rn, ts) ON v.rn = b.rn;

-- =====================================================================
-- TASK 9. Delete baggage checks created before 2023-06-01 with result 'Not checked'
-- =====================================================================
DELETE FROM baggage_check
WHERE created_at < '2023-06-01' AND check_result = 'Not checked';
SELECT count(*) AS left_rows FROM baggage_check
WHERE created_at < '2023-06-01' AND check_result = 'Not checked';                -- must be 0

-- =====================================================================
-- TASK 10. Delete airports with NULL state and city 'Mlawe' or 'Kepuh'
-- =====================================================================
DELETE FROM airport
WHERE state IS NULL AND city IN ('Mlawe', 'Kepuh');
SELECT * FROM airport WHERE city IN ('Mlawe', 'Kepuh');                          -- empty

-- =====================================================================
-- TASK 11. Insert a new unchecked baggage record and return its id and created_at
-- =====================================================================
INSERT INTO baggage_check (check_result, booking_id, passenger_id)
SELECT 'Not checked', booking_id, passenger_id FROM booking ORDER BY booking_id LIMIT 1
RETURNING baggage_check_id, created_at;

-- =====================================================================
-- TASK 12. Convert all country names in airline to uppercase
-- =====================================================================
UPDATE airline SET airline_country = UPPER(airline_country);
SELECT DISTINCT airline_country FROM airline;

-- =====================================================================
-- TASK 13. airline_id = 5 -> name 'Global Airways', country 'United Kingdom', updated_at = today
-- =====================================================================
UPDATE airline
SET airline_name    = 'Global Airways',
    airline_country = 'United Kingdom',
    updated_at      = CURRENT_DATE
WHERE airline_id = 5;
SELECT * FROM airline WHERE airline_id = 5;

-- =====================================================================
-- TASK 14. state = 'Capital District' for Astana, London, Tokyo
-- =====================================================================
UPDATE airport
SET state = 'Capital District'
WHERE city IN ('Astana', 'London', 'Tokyo');
SELECT * FROM airport WHERE city IN ('Astana', 'London', 'Tokyo');

-- =====================================================================
-- TASK 15. Baggage checks created in March 2024 with 'Not checked' -> 'Checked'
-- =====================================================================
UPDATE baggage_check
SET check_result = 'Checked'
WHERE created_at >= '2024-03-01' AND created_at < '2024-04-01'
  AND check_result = 'Not checked';
SELECT * FROM baggage_check
WHERE created_at >= '2024-03-01' AND created_at < '2024-04-01';
